services:
  nasaapp_db_container:
    container_name: nasaapp_db_container
    image: postgres
    volumes:
      - nasaapp_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
  nasaapp_postgres_container:
    container_name: nasaapp_postgres_container
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    env_file:
      - .env
  madcorp_web:
    container_name: madcorp_web
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - madcorp_db
    env_file:
      - .env
volumes:
 nasaapp_db_data: